package com.rabbit.aip.report;

import com.rabbit.aip.report.ReportDtos.AssessmentReport;
import com.rabbit.aip.report.ReportDtos.QuestionPerformance;
import com.rabbit.aip.report.ReportDtos.StudentResultPoint;
import com.rabbit.aip.report.ReportDtos.TeacherAnalyticsReport;
import com.rabbit.aip.report.ReportDtos.TeacherBatchAnalytics;
import com.rabbit.aip.report.ReportDtos.TeacherStudentComparison;
import com.rabbit.aip.report.ReportDtos.TeacherWeakTopic;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

final class ExcelReportWriter {

    byte[] write(AssessmentReport report) {
        List<List<Cell>> summary = List.of(
                row(header("Metric"), header("Value")),
                row(text("Assessment"), text(report.title())),
                row(text("Assessment ID"), text(report.assessmentId().toString())),
                row(text("Generated at"), text(report.generatedAt().toString())),
                row(text("Generated by"), text(report.generatedBy())),
                row(text("Submissions"), number(report.submissions())),
                row(text("Average percentage"), number(report.averagePercentage())),
                row(text("Highest percentage"), number(report.highestPercentage())),
                row(text("Lowest percentage"), number(report.lowestPercentage())),
                row(text("Pass rate"), number(report.passRate()))
        );
        List<List<Cell>> students = new ArrayList<>();
        students.add(row(
                header("Student"),
                header("Submitted at"),
                header("Score"),
                header("Maximum score"),
                header("Percentage"),
                header("Grade"),
                header("Progress")
        ));
        for (StudentResultPoint result : report.studentResults()) {
            students.add(row(
                    text(result.studentName()),
                    text(result.submittedAt().toString()),
                    number(result.score()),
                    number(result.maxScore()),
                    number(result.percentage()),
                    text(result.grade()),
                    text(result.trajectory())
            ));
        }
        List<List<Cell>> questions = new ArrayList<>();
        questions.add(row(
                header("Code"),
                header("Question"),
                header("Difficulty"),
                header("Responses"),
                header("Correct rate"),
                header("Difficulty index"),
                header("Discrimination index"),
                header("Quality")
        ));
        for (QuestionPerformance question : report.questionAnalytics()) {
            questions.add(row(
                    text(question.code()),
                    text(question.stem()),
                    text(question.difficulty().name()),
                    number(question.responseCount()),
                    number(question.correctRate()),
                    number(question.difficultyIndex()),
                    number(question.discriminationIndex()),
                    text(question.poorQuality() ? "REVIEW" : "HEALTHY")
            ));
        }
        return workbook(List.of(
                new Sheet("Summary", summary),
                new Sheet("Student Results", students),
                new Sheet("Question Analytics", questions)
        ));
    }

    byte[] write(TeacherAnalyticsReport report) {
        List<List<Cell>> summary = List.of(
                row(header("Metric"), header("Value")),
                row(text("Teacher scope"), text(report.teacherName())),
                row(text("Generated at"), text(report.generatedAt().toString())),
                row(text("Assessments"), number(report.assessmentCount())),
                row(text("Published submissions"), number(report.publishedSubmissions())),
                row(text("Average percentage"), number(report.averagePercentage())),
                row(text("Weak topics"), number(report.weakTopicCount()))
        );
        List<List<Cell>> batches = new ArrayList<>();
        batches.add(row(
                header("Batch"),
                header("Students"),
                header("Assessments"),
                header("Submissions"),
                header("Students attempted"),
                header("Completion rate"),
                header("Average percentage"),
                header("Pass rate")
        ));
        for (TeacherBatchAnalytics batch : report.batches()) {
            batches.add(row(
                    text(batch.batchName()),
                    number(batch.studentCount()),
                    number(batch.assessmentCount()),
                    number(batch.submissionCount()),
                    number(batch.studentsAttempted()),
                    number(batch.completionRate()),
                    number(batch.averagePercentage()),
                    number(batch.passRate())
            ));
        }
        List<List<Cell>> students = new ArrayList<>();
        students.add(row(
                header("Rank"),
                header("Student"),
                header("Batch"),
                header("Published attempts"),
                header("Average percentage"),
                header("Best percentage"),
                header("Pass rate"),
                header("Progress"),
                header("At risk")
        ));
        for (TeacherStudentComparison student : report.students()) {
            students.add(row(
                    number(student.rank()),
                    text(student.studentName()),
                    text(student.batchName()),
                    number(student.publishedAttempts()),
                    number(student.averagePercentage()),
                    number(student.bestPercentage()),
                    number(student.passRate()),
                    text(student.trajectory()),
                    text(student.atRisk() ? "YES" : "NO")
            ));
        }
        List<List<Cell>> weakTopics = new ArrayList<>();
        weakTopics.add(row(
                header("Subject"),
                header("Topic"),
                header("Questions"),
                header("Responses"),
                header("Average marks percentage"),
                header("Correct rate"),
                header("Average time seconds"),
                header("Status")
        ));
        for (TeacherWeakTopic topic : report.weakTopics()) {
            weakTopics.add(row(
                    text(topic.subjectName()),
                    text(topic.topicName()),
                    number(topic.questionCount()),
                    number(topic.responseCount()),
                    number(topic.averageMarksPercentage()),
                    number(topic.correctRate()),
                    number(topic.averageTimeSeconds()),
                    text(topic.weak() ? "WEAK" : "ON TRACK")
            ));
        }
        return workbook(List.of(
                new Sheet("Summary", summary),
                new Sheet("Batch Analytics", batches),
                new Sheet("Student Comparison", students),
                new Sheet("Weak Topics", weakTopics)
        ));
    }

    private byte[] workbook(List<Sheet> sheets) {
        try {
            ByteArrayOutputStream bytes = new ByteArrayOutputStream();
            try (ZipOutputStream zip = new ZipOutputStream(bytes)) {
                entry(zip, "[Content_Types].xml", contentTypes(sheets.size()));
                entry(zip, "_rels/.rels", rootRelationships());
                entry(zip, "docProps/app.xml", appProperties(sheets));
                entry(zip, "docProps/core.xml", coreProperties());
                entry(zip, "xl/workbook.xml", workbookXml(sheets));
                entry(zip, "xl/_rels/workbook.xml.rels", workbookRelationships(sheets.size()));
                entry(zip, "xl/styles.xml", styles());
                for (int index = 0; index < sheets.size(); index++) {
                    entry(
                            zip,
                            "xl/worksheets/sheet" + (index + 1) + ".xml",
                            sheetXml(sheets.get(index).rows())
                    );
                }
            }
            return bytes.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("Excel report could not be created.", exception);
        }
    }

    private String sheetXml(List<List<Cell>> rows) {
        int maxColumns = rows.stream().mapToInt(List::size).max().orElse(1);
        StringBuilder xml = new StringBuilder(
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                        + "<worksheet xmlns=\"http://schemas.openxmlformats.org/"
                        + "spreadsheetml/2006/main\">"
                        + "<sheetViews><sheetView workbookViewId=\"0\">"
                        + "<pane ySplit=\"1\" topLeftCell=\"A2\" activePane=\"bottomLeft\" "
                        + "state=\"frozen\"/></sheetView></sheetViews>"
                        + "<sheetFormatPr defaultRowHeight=\"15\"/><cols>"
        );
        for (int column = 1; column <= maxColumns; column++) {
            xml.append("<col min=\"").append(column)
                    .append("\" max=\"").append(column)
                    .append("\" width=\"22\" customWidth=\"1\"/>");
        }
        xml.append("</cols><sheetData>");
        for (int rowIndex = 0; rowIndex < rows.size(); rowIndex++) {
            int rowNumber = rowIndex + 1;
            xml.append("<row r=\"").append(rowNumber).append("\">");
            List<Cell> row = rows.get(rowIndex);
            for (int column = 0; column < row.size(); column++) {
                Cell cell = row.get(column);
                String reference = columnName(column + 1) + rowNumber;
                if (cell.numeric()) {
                    xml.append("<c r=\"").append(reference)
                            .append("\" s=\"").append(cell.style())
                            .append("\"><v>").append(xml(cell.value()))
                            .append("</v></c>");
                } else {
                    xml.append("<c r=\"").append(reference)
                            .append("\" t=\"inlineStr\" s=\"").append(cell.style())
                            .append("\"><is><t xml:space=\"preserve\">")
                            .append(xml(cell.value()))
                            .append("</t></is></c>");
                }
            }
            xml.append("</row>");
        }
        String lastCell = columnName(maxColumns) + Math.max(1, rows.size());
        return xml.append("</sheetData><autoFilter ref=\"A1:")
                .append(lastCell)
                .append("\"/></worksheet>")
                .toString();
    }

    private String contentTypes(int sheetCount) {
        StringBuilder xml = new StringBuilder(
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                        + "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">"
                        + "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>"
                        + "<Default Extension=\"xml\" ContentType=\"application/xml\"/>"
                        + "<Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>"
                        + "<Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/>"
                        + "<Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>"
                        + "<Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>"
        );
        for (int index = 1; index <= sheetCount; index++) {
            xml.append("<Override PartName=\"/xl/worksheets/sheet")
                    .append(index)
                    .append(".xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>");
        }
        return xml.append("</Types>").toString();
    }

    private String workbookXml(List<Sheet> sheets) {
        StringBuilder xml = new StringBuilder(
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                        + "<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" "
                        + "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets>"
        );
        for (int index = 0; index < sheets.size(); index++) {
            xml.append("<sheet name=\"").append(xml(sheets.get(index).name()))
                    .append("\" sheetId=\"").append(index + 1)
                    .append("\" r:id=\"rId").append(index + 1).append("\"/>");
        }
        return xml.append("</sheets></workbook>").toString();
    }

    private String workbookRelationships(int sheetCount) {
        StringBuilder xml = new StringBuilder(
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                        + "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"
        );
        for (int index = 1; index <= sheetCount; index++) {
            xml.append("<Relationship Id=\"rId").append(index)
                    .append("\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" "
                            + "Target=\"worksheets/sheet")
                    .append(index).append(".xml\"/>");
        }
        return xml.append("<Relationship Id=\"rId")
                .append(sheetCount + 1)
                .append("\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/>")
                .append("</Relationships>")
                .toString();
    }

    private String rootRelationships() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                + "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"
                + "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/>"
                + "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/>"
                + "<Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/>"
                + "</Relationships>";
    }

    private String coreProperties() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                + "<cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" "
                + "xmlns:dc=\"http://purl.org/dc/elements/1.1/\">"
                + "<dc:creator>Rabbit AiP</dc:creator><dc:title>Assessment report</dc:title>"
                + "</cp:coreProperties>";
    }

    private String appProperties(List<Sheet> sheets) {
        StringBuilder titles = new StringBuilder();
        sheets.forEach(sheet -> titles.append("<vt:lpstr>")
                .append(xml(sheet.name()))
                .append("</vt:lpstr>"));
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                + "<Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\">"
                + "<Application>Rabbit AiP</Application>"
                + "<HeadingPairs><vt:vector xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\" size=\"2\" baseType=\"variant\">"
                + "<vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant>"
                + "<vt:variant><vt:i4>" + sheets.size() + "</vt:i4></vt:variant>"
                + "</vt:vector></HeadingPairs>"
                + "<TitlesOfParts><vt:vector xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\" size=\""
                + sheets.size() + "\" baseType=\"lpstr\">" + titles
                + "</vt:vector></TitlesOfParts></Properties>";
    }

    private String styles() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
                + "<styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">"
                + "<fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Aptos\"/></font>"
                + "<font><b/><color rgb=\"FFFFFFFF\"/><sz val=\"11\"/><name val=\"Aptos\"/></font></fonts>"
                + "<fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill>"
                + "<fill><patternFill patternType=\"gray125\"/></fill>"
                + "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF5936C8\"/><bgColor indexed=\"64\"/></patternFill></fill></fills>"
                + "<borders count=\"1\"><border><left/><right/><top/><bottom/><diagonal/></border></borders>"
                + "<cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs>"
                + "<cellXfs count=\"2\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/>"
                + "<xf numFmtId=\"0\" fontId=\"1\" fillId=\"2\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\"/></cellXfs>"
                + "<cellStyles count=\"1\"><cellStyle name=\"Normal\" xfId=\"0\" builtinId=\"0\"/></cellStyles>"
                + "</styleSheet>";
    }

    private void entry(ZipOutputStream zip, String name, String content)
            throws IOException {
        ZipEntry entry = new ZipEntry(name);
        entry.setTime(0);
        zip.putNextEntry(entry);
        zip.write(content.getBytes(StandardCharsets.UTF_8));
        zip.closeEntry();
    }

    private List<Cell> row(Cell... cells) {
        return List.of(cells);
    }

    private Cell header(String value) {
        return new Cell(value, false, 1);
    }

    private Cell text(String value) {
        return new Cell(value == null ? "" : value, false, 0);
    }

    private Cell number(Object value) {
        return new Cell(value == null ? "0" : value.toString(), true, 0);
    }

    private String columnName(int index) {
        StringBuilder result = new StringBuilder();
        int value = index;
        while (value > 0) {
            int remainder = (value - 1) % 26;
            result.insert(0, (char) ('A' + remainder));
            value = (value - 1) / 26;
        }
        return result.toString();
    }

    private String xml(String value) {
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&apos;");
    }

    private record Sheet(String name, List<List<Cell>> rows) {
    }

    private record Cell(String value, boolean numeric, int style) {
    }
}
