package com.rabbit.aip.report;

import com.rabbit.aip.report.ReportDtos.AssessmentReport;
import com.rabbit.aip.report.ReportDtos.QuestionPerformance;
import com.rabbit.aip.report.ReportDtos.StudentResultPoint;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.text.Normalizer;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

final class PdfReportWriter {

    private static final int LINES_PER_PAGE = 48;
    private static final int LINE_WIDTH = 84;

    byte[] write(AssessmentReport report) {
        List<String> lines = documentLines(report);
        List<List<String>> pages = new ArrayList<>();
        for (int index = 0; index < lines.size(); index += LINES_PER_PAGE) {
            pages.add(lines.subList(
                    index,
                    Math.min(index + LINES_PER_PAGE, lines.size())
            ));
        }
        if (pages.isEmpty()) pages.add(List.of("Rabbit AiP assessment report"));
        return pdf(pages);
    }

    private List<String> documentLines(AssessmentReport report) {
        List<String> source = new ArrayList<>();
        source.add("RABBIT AiP - ASSESSMENT REPORT");
        source.add(report.title());
        source.add("");
        source.add("Generated: " + DateTimeFormatter.ISO_INSTANT.format(report.generatedAt()));
        source.add("Generated by: " + report.generatedBy());
        source.add("Assessment ID: " + report.assessmentId());
        source.add("");
        source.add(String.format(
                Locale.ROOT,
                "Submissions: %d   Average: %s%%   Highest: %s%%   Lowest: %s%%   Pass rate: %s%%",
                report.submissions(),
                report.averagePercentage(),
                report.highestPercentage(),
                report.lowestPercentage(),
                report.passRate()
        ));
        source.add("");
        source.add("STUDENT RESULTS");
        source.add("Student | Submitted (UTC) | Score | Percentage | Grade | Progress");
        for (StudentResultPoint result : report.studentResults()) {
            source.add(String.format(
                    Locale.ROOT,
                    "%s | %s | %s/%s | %s%% | %s | %s",
                    result.studentName(),
                    DateTimeFormatter.ISO_INSTANT.format(result.submittedAt()),
                    result.score(),
                    result.maxScore(),
                    result.percentage(),
                    result.grade(),
                    result.trajectory()
            ));
        }
        source.add("");
        source.add("QUESTION PERFORMANCE");
        source.add("Code | Responses | Correct rate | Difficulty index | Discrimination | Quality");
        for (QuestionPerformance question : report.questionAnalytics()) {
            source.add(String.format(
                    Locale.ROOT,
                    "%s | %d | %s%% | %s | %s | %s",
                    question.code(),
                    question.responseCount(),
                    question.correctRate(),
                    question.difficultyIndex(),
                    question.discriminationIndex(),
                    question.poorQuality() ? "REVIEW" : "HEALTHY"
            ));
        }
        List<String> wrapped = new ArrayList<>();
        source.forEach(line -> wrapped.addAll(wrap(ascii(line))));
        return wrapped;
    }

    private List<String> wrap(String value) {
        if (value.length() <= LINE_WIDTH) return List.of(value);
        List<String> result = new ArrayList<>();
        String remaining = value;
        while (remaining.length() > LINE_WIDTH) {
            int split = remaining.lastIndexOf(' ', LINE_WIDTH);
            if (split < 1) split = LINE_WIDTH;
            result.add(remaining.substring(0, split));
            remaining = remaining.substring(split).trim();
        }
        result.add(remaining);
        return result;
    }

    private byte[] pdf(List<List<String>> pages) {
        int objectCount = 3 + pages.size() * 2;
        byte[][] objects = new byte[objectCount + 1][];
        objects[1] = bytes("<< /Type /Catalog /Pages 2 0 R >>");
        StringBuilder kids = new StringBuilder("[");
        for (int index = 0; index < pages.size(); index++) {
            kids.append(4 + index * 2).append(" 0 R ");
        }
        kids.append(']');
        objects[2] = bytes("<< /Type /Pages /Kids " + kids
                + " /Count " + pages.size() + " >>");
        objects[3] = bytes(
                "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
        );
        for (int index = 0; index < pages.size(); index++) {
            int pageObject = 4 + index * 2;
            int contentObject = pageObject + 1;
            objects[pageObject] = bytes(
                    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
                            + "/Resources << /Font << /F1 3 0 R >> >> "
                            + "/Contents " + contentObject + " 0 R >>"
            );
            byte[] stream = bytes(contentStream(pages.get(index)));
            objects[contentObject] = concat(
                    bytes("<< /Length " + stream.length + " >>\nstream\n"),
                    stream,
                    bytes("\nendstream")
            );
        }

        try {
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            output.write(bytes("%PDF-1.4\n"));
            long[] offsets = new long[objectCount + 1];
            for (int object = 1; object <= objectCount; object++) {
                offsets[object] = output.size();
                output.write(bytes(object + " 0 obj\n"));
                output.write(objects[object]);
                output.write(bytes("\nendobj\n"));
            }
            long xrefOffset = output.size();
            output.write(bytes("xref\n0 " + (objectCount + 1) + "\n"));
            output.write(bytes("0000000000 65535 f \n"));
            for (int object = 1; object <= objectCount; object++) {
                output.write(bytes(String.format(
                        Locale.ROOT, "%010d 00000 n \n", offsets[object]
                )));
            }
            output.write(bytes(
                    "trailer\n<< /Size " + (objectCount + 1)
                            + " /Root 1 0 R >>\nstartxref\n"
                            + xrefOffset + "\n%%EOF\n"
            ));
            return output.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("PDF report could not be created.", exception);
        }
    }

    private String contentStream(List<String> lines) {
        StringBuilder stream = new StringBuilder(
                "BT\n/F1 9 Tf\n48 790 Td\n13 TL\n"
        );
        for (String line : lines) {
            stream.append('(').append(pdfText(line)).append(") Tj\nT*\n");
        }
        return stream.append("ET").toString();
    }

    private String ascii(String value) {
        String normalized = Normalizer.normalize(
                value == null ? "" : value,
                Normalizer.Form.NFKD
        );
        return normalized.replaceAll("[^\\x20-\\x7E]", "?");
    }

    private String pdfText(String value) {
        return value.replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)");
    }

    private byte[] bytes(String value) {
        return value.getBytes(StandardCharsets.US_ASCII);
    }

    private byte[] concat(byte[]... values) {
        try {
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            for (byte[] value : values) output.write(value);
            return output.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException(exception);
        }
    }
}
