import type { Assessment, AssessmentQuestion, Question } from "./types";

export const questions: Question[] = [
  {
    id: "70c0ca56-4b58-47d9-8b41-3ac706afe611",
    code: "PHY-MEC-001",
    stem: "A body starts from rest and moves with constant acceleration. Which graph correctly represents its displacement against time?",
    type: "SINGLE_CORRECT",
    subject: "Physics",
    topic: "Motion in a Straight Line",
    subTopic: "Uniform acceleration",
    difficulty: "MEDIUM",
    bloomLevel: "APPLY",
    marks: 4,
    negativeMarks: 1,
    status: "APPROVED",
    version: 2,
    options: [
      { id: "p1", label: "A", text: "A straight line through the origin", correct: false },
      { id: "p2", label: "B", text: "A parabola opening upward", correct: true },
      { id: "p3", label: "C", text: "A horizontal line", correct: false },
      { id: "p4", label: "D", text: "A parabola opening downward", correct: false },
    ],
    explanation: "For constant acceleration from rest, s = ½at², so displacement varies quadratically with time.",
    author: "Ananya Rao",
    updatedAt: "29 Jul 2026",
  },
  {
    id: "a9971960-b9aa-4f32-9d8d-85ea65e5288c",
    code: "CHE-ORG-014",
    stem: "Which of the following compounds can exhibit geometrical isomerism?",
    type: "MULTIPLE_CORRECT",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    subTopic: "Isomerism",
    difficulty: "HARD",
    bloomLevel: "ANALYSE",
    marks: 4,
    negativeMarks: 1,
    status: "UNDER_REVIEW",
    version: 1,
    options: [
      { id: "c1", label: "A", text: "2-butene", correct: true },
      { id: "c2", label: "B", text: "1-butene", correct: false },
      { id: "c3", label: "C", text: "1,2-dichloroethene", correct: true },
      { id: "c4", label: "D", text: "2-methylpropene", correct: false },
    ],
    explanation: "Each carbon of the relevant double bond must have two different substituents.",
    author: "Sanjay Mehta",
    updatedAt: "28 Jul 2026",
  },
  {
    id: "bf4c68d7-f0a4-489e-b65b-c5409088aa93",
    code: "MAT-CAL-029",
    stem: "If f(x) = x³ − 3x, what are the stationary points of f?",
    type: "MULTIPLE_CORRECT",
    subject: "Mathematics",
    topic: "Differential Calculus",
    difficulty: "MEDIUM",
    bloomLevel: "APPLY",
    marks: 4,
    negativeMarks: 1,
    status: "DRAFT",
    version: 1,
    options: [
      { id: "m1", label: "A", text: "x = −1", correct: true },
      { id: "m2", label: "B", text: "x = 0", correct: false },
      { id: "m3", label: "C", text: "x = 1", correct: true },
      { id: "m4", label: "D", text: "x = 3", correct: false },
    ],
    explanation: "f′(x) = 3x² − 3 = 0 gives x = ±1.",
    author: "Ananya Rao",
    updatedAt: "27 Jul 2026",
  },
  {
    id: "f3a5671c-d4c3-47d9-a022-ec01670f0548",
    code: "BIO-CEL-007",
    stem: "Which organelle is primarily responsible for ATP production in a eukaryotic cell?",
    type: "SINGLE_CORRECT",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "EASY",
    bloomLevel: "REMEMBER",
    marks: 2,
    negativeMarks: 0.5,
    status: "PUBLISHED",
    version: 1,
    options: [
      { id: "b1", label: "A", text: "Golgi apparatus", correct: false },
      { id: "b2", label: "B", text: "Mitochondrion", correct: true },
      { id: "b3", label: "C", text: "Lysosome", correct: false },
      { id: "b4", label: "D", text: "Nucleus", correct: false },
    ],
    explanation: "Oxidative phosphorylation in mitochondria produces most cellular ATP.",
    author: "Priya Menon",
    updatedAt: "24 Jul 2026",
  },
];

export const assessments: Assessment[] = [
  {
    id: "jee-physics-04",
    title: "JEE Physics — Kinematics",
    code: "JEE-PHY-04",
    type: "Chapter Test",
    subject: "Physics",
    durationMinutes: 45,
    questionCount: 20,
    totalMarks: 80,
    status: "SCHEDULED",
    startAt: "30 Jul, 10:00 AM",
    endAt: "30 Jul, 11:00 AM",
  },
  {
    id: "neet-bio-02",
    title: "NEET Biology — Cell Structure",
    code: "NEET-BIO-02",
    type: "Practice Assessment",
    subject: "Biology",
    durationMinutes: 30,
    questionCount: 15,
    totalMarks: 60,
    status: "PUBLISHED",
  },
  {
    id: "cat-quant-01",
    title: "CAT Quant — Arithmetic",
    code: "CAT-QA-01",
    type: "Mock Test",
    subject: "Quantitative Aptitude",
    durationMinutes: 40,
    questionCount: 22,
    totalMarks: 66,
    status: "DRAFT",
  },
];

export const assessmentQuestions: AssessmentQuestion[] = [
  {
    id: "q1",
    stem: "A car accelerates uniformly from 10 m/s to 20 m/s in 5 seconds. What distance does it cover in this interval?",
    type: "SINGLE_CORRECT",
    marks: 4,
    options: [
      { id: "q1a", label: "A", text: "50 m" },
      { id: "q1b", label: "B", text: "75 m" },
      { id: "q1c", label: "C", text: "100 m" },
      { id: "q1d", label: "D", text: "150 m" },
    ],
  },
  {
    id: "q2",
    stem: "Which statements are true for a body moving with uniform velocity?",
    type: "MULTIPLE_CORRECT",
    marks: 4,
    options: [
      { id: "q2a", label: "A", text: "Its acceleration is zero" },
      { id: "q2b", label: "B", text: "It covers equal displacement in equal intervals" },
      { id: "q2c", label: "C", text: "Its speed must continuously increase" },
      { id: "q2d", label: "D", text: "Its velocity–time graph is horizontal" },
    ],
  },
  {
    id: "q3",
    stem: "The slope of a displacement–time graph at a given instant represents:",
    type: "SINGLE_CORRECT",
    marks: 4,
    options: [
      { id: "q3a", label: "A", text: "Acceleration" },
      { id: "q3b", label: "B", text: "Velocity" },
      { id: "q3c", label: "C", text: "Force" },
      { id: "q3d", label: "D", text: "Momentum" },
    ],
  },
  {
    id: "q4",
    stem: "An object is thrown vertically upwards. At its highest point, which statement is correct?",
    type: "SINGLE_CORRECT",
    marks: 4,
    options: [
      { id: "q4a", label: "A", text: "Velocity and acceleration are both zero" },
      { id: "q4b", label: "B", text: "Velocity is zero, acceleration is downward" },
      { id: "q4c", label: "C", text: "Velocity is upward, acceleration is zero" },
      { id: "q4d", label: "D", text: "Velocity and acceleration are both upward" },
    ],
  },
];
