import type { FeatureFlag, OperationalSnapshot } from "./types";

export const demoOperationalSnapshot: OperationalSnapshot = {
  overallStatus: "READY_WITH_ACTIONS",
  generatedAt: new Date().toISOString(),
  releaseVersion: "1.0.0",
  environment: "pilot",
  uptimeSeconds: 18420,
  dependencies: [
    { name: "PostgreSQL", status: "UP", latencyMs: 4, detail: "Primary database reachable" },
    { name: "Redis", status: "UP", latencyMs: 2, detail: "Rate-limit and cache store reachable" },
    { name: "RabbitMQ", status: "UP", latencyMs: 3, detail: "Notification queue reachable" },
    { name: "MinIO", status: "UP", latencyMs: 8, detail: "Question asset store reachable" },
  ],
  traffic: {
    requests: 12482,
    serverErrors: 3,
    errorRate: 0.02,
    averageLatencyMs: 84.3,
    rateLimitedRequests: 17,
  },
  capacity: {
    databaseActiveConnections: 3,
    databaseIdleConnections: 7,
    databaseMaximumConnections: 20,
    jvmUsedMemoryMb: 286,
    jvmMaximumMemoryMb: 768,
    availableProcessors: 4,
  },
  workflows: {
    activeAssessmentAttempts: 12,
    pendingResultPublications: 8,
    pendingQuestionReviews: 6,
    pendingAssessmentReviews: 2,
    queuedNotifications: 4,
    failedNotifications: 1,
    overdueReviewItems: 0,
  },
  readiness: [
    {
      key: "DEPENDENCIES",
      label: "Core dependencies",
      status: "PASS",
      detail: "PostgreSQL, Redis, RabbitMQ, and MinIO responded.",
    },
    {
      key: "FAILED_DELIVERIES",
      label: "Notification delivery backlog",
      status: "WARN",
      detail: "1 failed delivery record needs review.",
    },
    {
      key: "REVIEW_SLA",
      label: "Governance review SLA",
      status: "PASS",
      detail: "No review item is older than 48 hours.",
    },
  ],
};

export const demoFeatureFlags: FeatureFlag[] = [
  {
    key: "PDF_EXPORTS",
    label: "PDF report exports",
    description: "Allow styled PDF downloads for governed assessment reports.",
    enabled: true,
    rolloutPercentage: 100,
    activeForCurrentUser: true,
  },
  {
    key: "EXCEL_EXPORTS",
    label: "Excel report exports",
    description: "Allow native XLSX downloads for governed assessment reports.",
    enabled: true,
    rolloutPercentage: 100,
    activeForCurrentUser: true,
  },
  {
    key: "OPERATIONS_CONSOLE",
    label: "Operations console",
    description: "Expose tenant-scoped GA health, traffic, and workflow indicators.",
    enabled: true,
    rolloutPercentage: 100,
    activeForCurrentUser: true,
  },
  {
    key: "PILOT_MODE",
    label: "Controlled pilot mode",
    description: "Show pilot-readiness controls while Release 1.0 is introduced.",
    enabled: true,
    rolloutPercentage: 100,
    activeForCurrentUser: true,
  },
  {
    key: "BULK_IMPORTS",
    label: "Bulk imports",
    description: "Enable guarded question and user bulk-import workflows.",
    enabled: false,
    rolloutPercentage: 0,
    activeForCurrentUser: false,
  },
  {
    key: "EXTERNAL_DELIVERY",
    label: "External notification delivery",
    description: "Enable provider-backed email and SMS delivery adapters.",
    enabled: false,
    rolloutPercentage: 0,
    activeForCurrentUser: false,
  },
];
